// frontend/src/pages/BracketChallenge.jsx
import { useEffect, useState, useCallback } from 'react';
import { useLocation } from 'react-router-dom';
import MatchupCard from '../components/MatchupCard';
import { predictMatch, submitUserPrediction } from '../api/client';
import { buildR32 } from '../data/wc2026';

// FIFA World Cup 2026 — Predicted Round of 32
// Based on official draw (Dec 2024): 1A vs 2B, 1B vs 2A, etc.
const INITIAL_R32 = [
  { id: 'r32_1',  team1: 'Mexico',               team2: 'Canada' },
  { id: 'r32_2',  team1: 'Switzerland',           team2: 'South Korea' },
  { id: 'r32_3',  team1: 'Brazil',                team2: 'Turkey' },
  { id: 'r32_4',  team1: 'USA',                   team2: 'Morocco' },
  { id: 'r32_5',  team1: 'Germany',               team2: 'Japan' },
  { id: 'r32_6',  team1: 'Netherlands',           team2: 'Ecuador' },
  { id: 'r32_7',  team1: 'Belgium',               team2: 'Uruguay' },
  { id: 'r32_8',  team1: 'Spain',                 team2: 'Egypt' },
  { id: 'r32_9',  team1: 'France',                team2: 'Austria' },
  { id: 'r32_10', team1: 'Argentina',             team2: 'Senegal' },
  { id: 'r32_11', team1: 'Portugal',              team2: 'Croatia' },
  { id: 'r32_12', team1: 'England',               team2: 'Colombia' },
  { id: 'r32_13', team1: 'South Africa',          team2: 'Bosnia and Herzegovina' },
  { id: 'r32_14', team1: 'Scotland',              team2: 'Paraguay' },
  { id: 'r32_15', team1: 'Ivory Coast',           team2: 'Sweden' },
  { id: 'r32_16', team1: 'Iran',                  team2: 'Norway' },
];

const ROUNDS = ['Round of 32', 'Round of 16', 'Quarter-finals', 'Semi-finals', 'Final'];
const TOTAL_MATCHUPS = 16 + 8 + 4 + 2 + 1; // 31

// Stable mapping from matchup ID → DB match ID (seeded in order on the backend)
const MATCH_ID_MAP = {
  r32_1: 1,  r32_2: 2,  r32_3: 3,  r32_4: 4,
  r32_5: 5,  r32_6: 6,  r32_7: 7,  r32_8: 8,
  r32_9: 9,  r32_10: 10, r32_11: 11, r32_12: 12,
  r32_13: 13, r32_14: 14, r32_15: 15, r32_16: 16,
  r16_1: 17, r16_2: 18, r16_3: 19, r16_4: 20,
  r16_5: 21, r16_6: 22, r16_7: 23, r16_8: 24,
  qf_1: 25, qf_2: 26, qf_3: 27, qf_4: 28,
  sf_1: 29, sf_2: 30,
  f_1: 31,
};

// card height + gap ≈ 82px — used to compute vertical bracket spacing
const CELL = 82;

function buildEmptyRound(n, prefix) {
  return Array.from({ length: n }, (_, i) => ({
    id: `${prefix}_${i + 1}`, team1: null, team2: null, prob1: null, prob2: null,
  }));
}

function ModelBanner() {
  const stats = [
    { label: 'Training matches', value: '49,287' },
    { label: 'Model', value: 'XGBoost' },
    { label: 'Features', value: '9' },
    { label: '2018 WC accuracy', value: '40.6%' },
    { label: '2022 WC accuracy', value: '39.1%' },
    { label: 'Baseline (random)', value: '33.3%' },
  ];
  return (
    <div className="border border-slate-200 rounded-2xl bg-white p-6 mb-8 shadow-sm">
      <div className="flex flex-wrap items-start justify-between gap-6">
        <div className="max-w-lg">
          <p className="text-xs font-bold uppercase tracking-widest text-green-600 mb-1">Powered by ML</p>
          <h2 className="text-lg font-bold text-slate-900 mb-2">How the predictions work</h2>
          <p className="text-sm text-slate-500 leading-relaxed">
            Each matchup probability is generated by an XGBoost classifier trained on 49,287 international results from 1872–2024. Features include ELO ratings (tournament-weighted), recent form (last 5 matches), and head-to-head records. All World Cup matches are treated as neutral-ground.
          </p>
        </div>
        <div className="flex flex-wrap gap-3">
          {stats.map(s => (
            <div key={s.label} className="bg-slate-50 border border-slate-200 rounded-xl px-4 py-3 text-center min-w-[90px]">
              <div className="text-lg font-bold text-green-600">{s.value}</div>
              <div className="text-[11px] text-slate-400 mt-0.5">{s.label}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

const SUBMISSION_KEY = 'wc2026_bracket_submission';

function getSavedSubmission() {
  try { return JSON.parse(localStorage.getItem(SUBMISSION_KEY)) || null; } catch { return null; }
}

export default function BracketChallenge() {
  const location = useLocation();
  const [username, setUsername] = useState(() => getSavedSubmission()?.username || '');
  const [submitted, setSubmitted] = useState(() => !!getSavedSubmission()?.username);
  const [submitting, setSubmitting] = useState(false);
  const [submitMsg, setSubmitMsg] = useState('');

  // Use group-stage picks from router state, localStorage, or default R32
  const r32Source = (() => {
    if (location.state?.r32) return location.state.r32;
    try {
      const saved = localStorage.getItem('wc2026_group_picks');
      if (saved) {
        const { selections, thirdSelected } = JSON.parse(saved);
        const allDone = Object.values(selections).every(s => s.length === 2);
        if (allDone && thirdSelected?.length === 8) {
          const groupResults = Object.fromEntries(
            Object.entries(selections).map(([g, s]) => [g, { winner: s[0], runnerUp: s[1] }])
          );
          return buildR32(groupResults, thirdSelected);
        }
      }
    } catch { /* fall through */ }
    return INITIAL_R32;
  })();

  const [bracket, setBracket] = useState([
    r32Source.map(m => ({ ...m, prob1: null, prob2: null })),
    buildEmptyRound(8, 'r16'),
    buildEmptyRound(4, 'qf'),
    buildEmptyRound(2, 'sf'),
    buildEmptyRound(1, 'f'),
  ]);

  const [picks, setPicks] = useState({});
  const [loadingProbs, setLoadingProbs] = useState({});

  const fetchProbs = useCallback(async (matchupId, team1, team2) => {
    if (!team1 || !team2) return;
    setLoadingProbs(p => ({ ...p, [matchupId]: true }));
    try {
      const { data } = await predictMatch(team1, team2, true);
      setBracket(prev => prev.map(round =>
        round.map(m =>
          m.id === matchupId
            ? { ...m, prob1: data.prob_home_win, prob2: data.prob_away_win }
            : m
        )
      ));
    } catch {
      // silently fail
    } finally {
      setLoadingProbs(p => ({ ...p, [matchupId]: false }));
    }
  }, []);

  useEffect(() => {
    r32Source.forEach(m => fetchProbs(m.id, m.team1, m.team2));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fetchProbs]);

  const handlePick = useCallback((matchupId, winner) => {
    setPicks(prev => ({ ...prev, [matchupId]: winner }));

    setBracket(prev => {
      const next = prev.map(r => r.map(m => ({ ...m })));

      for (let roundIdx = 0; roundIdx < next.length - 1; roundIdx++) {
        const matchIdx = next[roundIdx].findIndex(m => m.id === matchupId);
        if (matchIdx === -1) continue;

        const nextMatchIdx = Math.floor(matchIdx / 2);
        const slot = matchIdx % 2 === 0 ? 'team1' : 'team2';
        const nextMatchup = next[roundIdx + 1][nextMatchIdx];

        if (nextMatchup[slot] !== winner) {
          nextMatchup[slot] = winner;
          nextMatchup.prob1 = null;
          nextMatchup.prob2 = null;

          setPicks(p => {
            const updated = { ...p };
            delete updated[nextMatchup.id];
            return updated;
          });

          if (nextMatchup.team1 && nextMatchup.team2) {
            setTimeout(() => fetchProbs(nextMatchup.id, nextMatchup.team1, nextMatchup.team2), 0);
          }
        }
        break;
      }
      return next;
    });
  }, [fetchProbs]);

  const handleSubmit = async () => {
    if (!username.trim()) return setSubmitMsg('Enter a username first');
    if (Object.keys(picks).length < TOTAL_MATCHUPS) {
      return setSubmitMsg(`Complete all ${TOTAL_MATCHUPS} picks first (${Object.keys(picks).length}/${TOTAL_MATCHUPS} done)`);
    }
    setSubmitting(true);
    setSubmitMsg('');
    try {
      const allMatchups = bracket.flat();
      await Promise.all(
        Object.entries(picks).map(([matchupId, winner]) => {
          const matchup = allMatchups.find(m => m.id === matchupId);
          const outcome = matchup && matchup.team2 === winner ? 'away_win' : 'home_win';
          const dbMatchId = MATCH_ID_MAP[matchupId];
          if (!dbMatchId) return Promise.resolve();
          return submitUserPrediction(username.trim(), dbMatchId, outcome).catch(() => null);
        })
      );
      localStorage.setItem(SUBMISSION_KEY, JSON.stringify({ username: username.trim() }));
      setSubmitted(true);
      setSubmitMsg('');
    } catch {
      setSubmitMsg('Something went wrong. Try again.');
    } finally {
      setSubmitting(false);
    }
  };

  const totalPicks = Object.keys(picks).length;
  const champion = picks[bracket[4][0]?.id];

  // Vertical spacing formula: each bracket level doubles the cell size
  const bracketGap = (roundIdx) =>
    roundIdx === 0 ? 6 : Math.pow(2, roundIdx) * CELL - 76;
  const bracketPadTop = (roundIdx) =>
    roundIdx === 0 ? 0 : Math.pow(2, roundIdx) * CELL / 2 - 38;

  return (
    <div className="max-w-none">
      {/* Page title */}
      <div className="max-w-5xl mx-auto mb-6">
        <p className="text-xs font-bold uppercase tracking-widest text-green-600 mb-1">FIFA World Cup 2026</p>
        <h1 className="text-3xl font-extrabold text-slate-900 mb-1">AI Bracket Challenge</h1>
        <p className="text-slate-500 text-sm">
          Pick the winner of every knockout match — from Round of 32 to the Final. AI win probabilities powered by XGBoost trained on 49k historical matches.
        </p>
      </div>

      {/* Model explanation banner */}
      <div className="max-w-5xl mx-auto">
        <ModelBanner />
      </div>

      {/* Username + progress + submit */}
      <div className="max-w-5xl mx-auto mb-8 flex flex-wrap items-center gap-3 bg-white border border-slate-200 rounded-2xl px-5 py-4 shadow-sm">
        <input
          type="text"
          placeholder="Your username"
          value={username}
          onChange={e => setUsername(e.target.value)}
          disabled={submitted}
          className="bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-slate-900 text-sm w-52 focus:outline-none focus:ring-2 focus:ring-green-500 disabled:opacity-50 placeholder:text-slate-400"
        />

        {/* Progress bar */}
        <div className="flex items-center gap-2 flex-1 min-w-48">
          <div className="flex-1 h-2 bg-slate-200 rounded-full overflow-hidden">
            <div
              className="h-full bg-green-500 rounded-full transition-all"
              style={{ width: `${(totalPicks / TOTAL_MATCHUPS) * 100}%` }}
            />
          </div>
          <span className="text-sm text-slate-500 whitespace-nowrap">{totalPicks}/{TOTAL_MATCHUPS} picks</span>
        </div>

        {champion && (
          <span className="text-sm font-bold text-amber-700 bg-amber-100 border border-amber-300 px-3 py-1 rounded-lg">
            {champion}
          </span>
        )}

        {!submitted ? (
          <button
            onClick={handleSubmit}
            disabled={submitting || totalPicks < TOTAL_MATCHUPS || !username.trim()}
            className="bg-green-600 hover:bg-green-500 disabled:bg-slate-200 disabled:text-slate-400 text-white font-semibold px-6 py-2.5 rounded-xl transition-colors text-sm whitespace-nowrap cursor-pointer disabled:cursor-not-allowed"
          >
            {submitting ? 'Submitting…' : 'Submit Bracket'}
          </button>
        ) : (
          <span className="text-green-600 font-semibold text-sm">Bracket submitted!</span>
        )}
        {submitMsg && <span className="text-red-500 text-sm">{submitMsg}</span>}
      </div>

      {/* Bracket — horizontally scrollable */}
      <div className="overflow-x-auto pb-8">
        <div className="flex gap-6 min-w-max px-4" style={{ alignItems: 'flex-start' }}>
          {bracket.map((round, roundIdx) => (
            <div key={roundIdx} className="flex flex-col">
              {/* Round label */}
              <div className="text-[11px] font-bold text-slate-400 uppercase tracking-widest mb-3 text-center w-44">
                {ROUNDS[roundIdx]}
              </div>

              {/* Matchup cards with computed spacing */}
              <div
                className="flex flex-col"
                style={{
                  gap: `${bracketGap(roundIdx)}px`,
                  paddingTop: `${bracketPadTop(roundIdx)}px`,
                }}
              >
                {round.map(matchup => (
                  <MatchupCard
                    key={matchup.id}
                    matchup={matchup}
                    onPick={handlePick}
                    userPick={picks[matchup.id]}
                    loadingProbs={!!loadingProbs[matchup.id]}
                  />
                ))}
              </div>
            </div>
          ))}

          {/* Champion slot */}
          <div className="flex flex-col">
            <div className="text-[11px] font-bold text-slate-400 uppercase tracking-widest mb-3 text-center w-44">
              Champion
            </div>
            <div style={{ paddingTop: `${bracketPadTop(5)}px` }}>
              <div className={`w-44 rounded-xl border-2 p-5 text-center transition-all ${
                champion ? 'border-amber-400 bg-amber-50 shadow-[0_4px_20px_rgba(251,191,36,0.25)]' : 'border-slate-200 bg-white'
              }`}>
                <div className="text-3xl mb-2">🏆</div>
                <div className={`text-sm font-bold leading-snug ${champion ? 'text-amber-700' : 'text-slate-400'}`}>
                  {champion || 'TBD'}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
